ENG-4684: Removed default value (current date) from date field
entando/app-engine pull request #106
Opened 2023-03-16 13:09 UTC by eugeniosant

2023-03-16 14:36 UTC, zonia3000 approved these changes

2023-03-16 15:04 UTC, entgigi requested changes

2023-03-16 15:04 UTC, entgigi commented on cms-plugin/src/main/java/com/agiletec/plugins/jacms/apsadmin/content/IntroNewContentAction.java
> -                            if (attr instanceof DateAttribute) {
shouldn't you add a test?

2023-03-20 17:41 UTC, eugeniosant commented on cms-plugin/src/main/java/com/agiletec/plugins/jacms/apsadmin/content/IntroNewContentAction.java
> -                            if (attr instanceof DateAttribute) {
done

2023-03-21 07:53 UTC, entgigi approved these changes
LGTM

2023-03-22 16:49 UTC, merged