ENG-5082: Fix bug uninstallation of complex bundle
entando/app-engine pull request #197
Opened 2023-07-31 16:08 UTC by eugeniosant

2023-08-02 08:46 UTC, mirkoPan approved these changes
LGTM

2023-08-02 09:02 UTC, entgigi requested changes

2023-08-02 09:02 UTC, entgigi commented on engine/src/main/java/org/entando/entando/aps/system/services/component/ComponentDeleteRequestRow.java
> +            Integer type1 = DELETION_ORDER.indexOf(i1.get(0).getType());
[MAJOR] this could be dangerous if the list is empty, you should manage this use case too.

2023-08-02 09:02 UTC, entgigi commented on engine/src/main/java/org/entando/entando/aps/system/services/component/ComponentService.java
> -                                        .code(code)
[MAJOR] this response object cannont be without code! ComponentManager will not work and in general you should return error only for a pair of code and type.

2023-08-02 09:02 UTC, entgigi commented on engine/src/main/java/org/entando/entando/aps/system/services/component/IComponentUsageService.java
> +        // nothing to do
why by default don't you impose an order? Are you sure you are not relying on an ordered input list?

2023-08-02 09:02 UTC, entgigi commented on engine/src/main/java/org/entando/entando/aps/system/services/page/PageService.java
> +    /*
[MAJOR] don't comment code, remove it ... we have git history if you want retrieve it...

2023-08-02 09:02 UTC, entgigi commented on versioning-plugin/src/main/java/com/agiletec/plugins/jpversioning/aps/system/services/versioning/VersioningDAO.java
> +            + "onlineversion, approved, username FROM jpversioning_versionedcontents ";
sorry i don't understand, is this really related to bug reported inside ENG-5082 ?

2023-08-02 15:36 UTC, eugeniosant commented on engine/src/main/java/org/entando/entando/aps/system/services/page/PageService.java
> +    /*
Removed block

2023-08-02 15:39 UTC, eugeniosant commented on engine/src/main/java/org/entando/entando/aps/system/services/component/IComponentUsageService.java
> +        // nothing to do
Only some components need to be ordered; for example labels, fragments, content templates and others don't need to be sorted. Only categories and pages are sorted

2023-08-02 15:39 UTC, eugeniosant commented on versioning-plugin/src/main/java/com/agiletec/plugins/jpversioning/aps/system/services/versioning/VersioningDAO.java
> +            + "onlineversion, approved, username FROM jpversioning_versionedcontents ";
I've found this problem when I've done an integration test of that issue ENG-5082

2023-08-02 15:41 UTC, eugeniosant commented on engine/src/main/java/org/entando/entando/aps/system/services/component/ComponentService.java
> -                                        .code(code)
I removed that code block because the component type is checked into the validator

2023-08-03 07:44 UTC, entgigi approved these changes
LGTM

2023-08-03 07:58 UTC, merged