ENG-4551 Insert CDS connector project into app-engine project
entando/app-engine pull request #75
Opened 2023-02-16 11:54 UTC by entgigi

2023-02-21 16:44 UTC, eugeniosant requested changes

2023-02-21 16:44 UTC, eugeniosant commented on cds-plugin/src/test/config/conf/security.properties
> +# Parameters for Argon2 algorithm encryption
This file can be removed (argon2 library removed)

2023-02-21 16:44 UTC, eugeniosant commented on cds-plugin/src/main/resources/spring/plugins/jpcds/aps/baseManagersConfig.xml
> +    <bean id="StorageManager" class="org.entando.entando.plugins.jpcds.aps.system.storage.CdsStorageManager">
Remove section

2023-02-21 16:44 UTC, eugeniosant commented on cds-plugin/src/test/config/resources/cms/documents/text_resource.txt
> +Entando is a low-code, component-based platform that opens the door for accelerated development of cloud Modern Applications that leverage the full potential of continuous integration/continuous deli
Is this file used in some test?

2023-02-21 16:44 UTC, eugeniosant commented on engine/src/main/java/org/entando/entando/aps/system/services/storage/LocalStorageManager.java
> -	private static final EntLogger logger = EntLogFactory.getSanitizedLogger(LocalStorageManager.class);
Why did the log class change?

2023-02-21 16:44 UTC, eugeniosant commented on cds-plugin/src/test/resources/document/architecture.txt
> +Entando App Engine: assemble micro frontends & microservices and compose them on a page.
Is this file used in some test?

2023-02-21 16:51 UTC, entgigi commented on engine/src/main/java/org/entando/entando/aps/system/services/storage/LocalStorageManager.java
> -	private static final EntLogger logger = EntLogFactory.getSanitizedLogger(LocalStorageManager.class);
aren't we using Slf4j everywhere?

2023-02-21 16:52 UTC, entgigi commented on cds-plugin/src/test/config/resources/cms/documents/text_resource.txt
> +Entando is a low-code, component-based platform that opens the door for accelerated development of cloud Modern Applications that leverage the full potential of continuous integration/continuous deli
removed

2023-02-21 16:52 UTC, entgigi commented on cds-plugin/src/main/resources/spring/plugins/jpcds/aps/baseManagersConfig.xml
> +    <bean id="StorageManager" class="org.entando.entando.plugins.jpcds.aps.system.storage.CdsStorageManager">
removed

2023-02-21 16:52 UTC, entgigi commented on cds-plugin/src/test/config/conf/security.properties
> +# Parameters for Argon2 algorithm encryption
removed

2023-02-21 16:54 UTC, entgigi commented on cds-plugin/src/test/resources/document/architecture.txt
> +Entando App Engine: assemble micro frontends & microservices and compose them on a page.
removed

2023-02-23 07:53 UTC, zonia3000 commented on cds-plugin/pom.xml
> +        <!-- xkè ??? -->
?

2023-02-23 07:53 UTC, zonia3000 commented on cds-plugin/src/main/java/org/entando/entando/plugins/jpcds/aps/system/storage/CdsFileAttributeViewDto.java
> +	private Map<String,String> lastModifiedTime;
indentation

2023-02-23 07:53 UTC, zonia3000 commented on cds-plugin/src/main/java/org/entando/entando/plugins/jpcds/aps/system/storage/CdsRemoteCaller.java
> +    private static final EntLogger logger = EntLogFactory.getSanitizedLogger(CdsRemoteCaller.class);
Can we use sl4j?

2023-02-23 07:53 UTC, zonia3000 commented on cds-plugin/src/main/java/org/entando/entando/plugins/jpcds/aps/system/storage/CdsRemoteCaller.java
> +         // FIXME doesn't work => return config.map(tc -> getTenantToken(tc,force)).orElse(getPrimaryToken(force));
?

2023-02-23 07:53 UTC, zonia3000 commented on cds-plugin/src/main/java/org/entando/entando/plugins/jpcds/aps/system/storage/CdsStorageManager.java
> +                    .path(CdsUrlUtils.getInternalSection(privateUrl)) // << this is part of bash url because we want check path traversal!!
bash -> base

2023-02-23 07:53 UTC, zonia3000 commented on cds-plugin/src/main/resources/spring/plugins/jpcds/aps/baseManagersConfig.xml
> +    -->
Can we remove this commented section?

2023-02-23 07:53 UTC, zonia3000 commented on engine/src/main/resources/spring/baseSystemConfig.xml
> +    <!--
Can we remove this commented section?

2023-02-23 08:04 UTC, entgigi commented on cds-plugin/pom.xml
> +        <!-- xkè ??? -->
removed

2023-02-23 08:08 UTC, entgigi commented on cds-plugin/src/main/java/org/entando/entando/plugins/jpcds/aps/system/storage/CdsRemoteCaller.java
> +    private static final EntLogger logger = EntLogFactory.getSanitizedLogger(CdsRemoteCaller.class);
yes for sure, that  is my bad

2023-02-23 08:09 UTC, entgigi commented on cds-plugin/src/main/java/org/entando/entando/plugins/jpcds/aps/system/storage/CdsRemoteCaller.java
> +         // FIXME doesn't work => return config.map(tc -> getTenantToken(tc,force)).orElse(getPrimaryToken(force));
It is something I want to talk with you about it ... I mentioned it to you days ago ...

2023-02-23 08:09 UTC, entgigi commented on cds-plugin/src/main/resources/spring/plugins/jpcds/aps/baseManagersConfig.xml
> +    -->
already removed

2023-02-23 08:10 UTC, entgigi commented on engine/src/main/resources/spring/baseSystemConfig.xml
> +    <!--
removed

2023-02-23 08:11 UTC, entgigi commented on cds-plugin/src/main/java/org/entando/entando/plugins/jpcds/aps/system/storage/CdsFileAttributeViewDto.java
> +	private Map<String,String> lastModifiedTime;
reformatted all file

2023-02-23 09:43 UTC, entgigi commented on engine/src/main/java/org/entando/entando/aps/system/services/storage/LocalStorageManager.java
> -	private static final EntLogger logger = EntLogFactory.getSanitizedLogger(LocalStorageManager.class);
talked with Eugenio and Sonia face2face we keep slf4j

2023-02-23 09:43 UTC, entgigi commented on cds-plugin/src/main/java/org/entando/entando/plugins/jpcds/aps/system/storage/CdsStorageManager.java
> +                    .path(CdsUrlUtils.getInternalSection(privateUrl)) // << this is part of bash url because we want check path traversal!!
done

2023-02-23 09:44 UTC, entgigi commented on cds-plugin/src/main/java/org/entando/entando/plugins/jpcds/aps/system/storage/CdsRemoteCaller.java
> +         // FIXME doesn't work => return config.map(tc -> getTenantToken(tc,force)).orElse(getPrimaryToken(force));
changed as you suggested tnx!

2023-02-23 10:21 UTC, zonia3000 approved these changes

2023-02-24 14:21 UTC, eugeniosant approved these changes

2023-02-24 14:46 UTC, merged